[package]
name = "ink_storage"
version = "3.0.0-rc5"
authors = ["Parity Technologies <admin@parity.io>", "Robin Freyler <robin@parity.io>"]
edition = "2018"

license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/paritytech/ink"
documentation = "https://docs.rs/ink_storage/"
homepage = "https://www.parity.io/"
description = "[ink!] Data structures to organize and manipulate ink! contract storage."
keywords = ["wasm", "parity", "webassembly", "blockchain", "edsl"]
categories = ["no-std", "embedded"]
include = ["Cargo.toml", "src/**/*.rs", "README.md", "LICENSE"]

[dependencies]
ink_env = { version = "3.0.0-rc5", path = "../env/", default-features = false }
ink_metadata = { version = "3.0.0-rc5", path = "../metadata/", default-features = false, features = ["derive"], optional = true }
ink_primitives = { version = "3.0.0-rc5", path = "../primitives/", default-features = false }
ink_storage_derive = { version = "3.0.0-rc5", path = "derive", default-features = false }
ink_prelude = { version = "3.0.0-rc5", path = "../prelude/", default-features = false }

scale = { package = "parity-scale-codec", version = "2", default-features = false, features = ["derive", "full"] }
derive_more = { version = "0.99", default-features = false, features = ["from", "display"] }
scale-info = { version = "1.0", default-features = false, features = ["derive"], optional = true }
cfg-if = "1.0"
array-init = { version = "2.0", default-features = false }

# Workaround: we actually just need criterion as a dev-dependency, but
# there is an issue with a doubly included std lib when executing
# `cargo check --no-default-features --target wasm32-unknown-unknown`.
# We haven't found a better solution yet.
criterion = { version = "0.3", optional = true }

[dev-dependencies]
quickcheck = "1.0"
quickcheck_macros = "1.0"
itertools = "0.10"
paste = "1.0"

[features]
default = ["std"]
std = [
    "criterion",
    "ink_metadata",
    "ink_metadata/std",
    "ink_env/std",
    "ink_prelude/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info",
    "scale-info/std",
]
ink-fuzz-tests = ["std"]
ink-experimental-engine = ["ink_env/ink-experimental-engine"]

[[bench]]
name = "bench_lazy"
path = "benches/bench_lazy.rs"
harness = false

[[bench]]
name = "bench_vec"
path = "benches/bench_vec.rs"
harness = false

[[bench]]
name = "bench_stash"
path = "benches/bench_stash.rs"
harness = false

[[bench]]
name = "bench_bitstash"
path = "benches/bench_bitstash.rs"
harness = false

[[bench]]
name = "bench_hashmap"
path = "benches/bench_hashmap.rs"
harness = false

[[bench]]
name = "bench_binary_heap"
path = "benches/bench_binary_heap.rs"
harness = false
